### ISSUE TITLE
Can't update to subtitle

### ISSUE THREAD

**Issue by gclsoft** [zhigang1992/ZGNavigationBarTitle#9]
```
- (void)updateTitleTo:(NSString *)title
{
    if ([self.navigationItem.titleView isKindOfClass:[ZGNavigationTitleView class]]) {
        [(ZGNavigationTitleView *) self.navigationItem.titleView setNavigationBarTitle:title];
    }
}

- (void)updateSubtitleTo:(NSString *)subtitle
{
    if ([self.navigationItem.titleView isKindOfClass:[ZGNavigationTitleView class]]) {
        [(ZGNavigationTitleView *) self.navigationItem.titleView setNavigationBarSubtitle:subtitle];
    }
}
```

why I can't use it, `[self.navigationItem.titleView isKindOfClass:[ZGNavigationTitleView class]]` is not YES everytime. How to solve it?
My demo is not push `[view.navigationController pushViewController:svc animated:YES];`, it's presentViewController `[view presentViewController:navcont animated:YES completion:NULL];`

**Comment by zhigang1992** [comment]
You have to wrap your vc in with a navigation controller which in this case should be
